// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400081 (Central Circle (pre-clear)), 52 anchors over 595yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400081()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400081,
        {
            { -403.23f, 52.99f, -66.06f },
            { -396.49f, 36.33f, -68.56f },
            { -390.67f, 30.38f, -68.83f },
            { -374.62f, 26.33f, -68.83f },
            { -358.38f, 21.58f, -68.83f },
            { -353.03f, 27.79f, -68.83f },
            { -355.10f, 44.34f, -77.25f },
            { -356.75f, 52.72f, -83.25f },
            { -360.49f, 59.79f, -88.63f },
            { -365.06f, 50.71f, -90.73f },
            { -363.58f, 42.73f, -95.60f },
            { -362.26f, 34.24f, -101.19f },
            { -360.28f, 25.05f, -108.43f },
            { -352.17f, 27.09f, -108.43f },
            { -355.30f, 44.06f, -116.78f },
            { -356.74f, 52.28f, -122.61f },
            { -359.23f, 60.08f, -128.22f },
            { -371.35f, 71.43f, -130.83f },
            { -366.41f, 80.27f, -131.27f },
            { -358.91f, 84.23f, -130.89f },
            { -343.09f, 79.22f, -131.24f },
            { -334.79f, 63.52f, -131.24f },
            { -330.00f, 47.22f, -129.78f },
            { -326.80f, 39.07f, -128.70f },
            { -319.82f, 34.56f, -124.65f },
            { -311.49f, 33.77f, -122.14f },
            { -301.79f, 40.33f, -118.10f },
            { -299.76f, 48.17f, -116.09f },
            { -303.15f, 56.10f, -113.02f },
            { -310.23f, 60.33f, -110.26f },
            { -318.38f, 59.64f, -107.94f },
            { -325.61f, 53.32f, -104.92f },
            { -327.01f, 44.19f, -101.71f },
            { -323.16f, 37.05f, -99.03f },
            { -315.81f, 33.83f, -96.57f },
            { -307.71f, 34.41f, -93.96f },
            { -301.56f, 40.07f, -91.53f },
            { -297.05f, 57.27f, -90.59f },
            { -294.73f, 73.85f, -91.04f },
            { -298.60f, 80.92f, -90.69f },
            { -299.04f, 89.74f, -90.90f },
            { -306.35f, 93.83f, -90.93f },
            { -323.12f, 94.03f, -90.59f },
            { -340.88f, 93.96f, -90.29f },
            { -357.99f, 92.84f, -90.48f },
            { -374.68f, 91.80f, -90.87f },
            { -391.67f, 92.64f, -90.40f },
            { -411.28f, 92.84f, -90.71f },
            { -419.59f, 89.83f, -90.70f },
            { -436.63f, 91.74f, -91.52f },
            { -445.02f, 91.18f, -92.47f },
            { -451.52f, 86.44f, -93.23f },
        });
}
