// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9016 (Bael'Gar), 24 anchors over 323yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9016()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9016,
        {
            { 468.97f, 15.67f, -70.32f },
            { 472.53f, 24.38f, -68.95f },
            { 488.61f, 18.83f, -69.81f },
            { 504.40f, 13.59f, -69.92f },
            { 520.67f, 9.70f, -69.63f },
            { 537.89f, 5.63f, -68.45f },
            { 553.98f, 2.10f, -68.65f },
            { 570.39f, -0.76f, -69.77f },
            { 588.60f, 11.92f, -68.99f },
            { 596.10f, 15.35f, -71.33f },
            { 595.76f, 24.99f, -71.92f },
            { 606.28f, 38.66f, -73.37f },
            { 617.56f, 52.56f, -72.83f },
            { 631.36f, 61.09f, -72.74f },
            { 636.60f, 67.72f, -73.04f },
            { 630.03f, 77.49f, -73.04f },
            { 639.72f, 80.10f, -72.73f },
            { 644.63f, 73.55f, -73.09f },
            { 653.02f, 88.18f, -73.07f },
            { 659.49f, 104.50f, -72.78f },
            { 659.06f, 113.93f, -72.79f },
            { 666.97f, 119.41f, -73.31f },
            { 677.82f, 135.20f, -72.59f },
            { 682.81f, 144.55f, -72.51f },
        });
}
