// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 8580 (Atal'alarion), 46 anchors over 590yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_8580()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 8580,
        {
            { -444.85f, 48.35f, -148.74f },
            { -449.27f, 32.49f, -148.73f },
            { -449.98f, 24.03f, -148.60f },
            { -435.19f, 17.07f, -148.59f },
            { -427.47f, 14.21f, -148.80f },
            { -411.21f, 19.19f, -148.80f },
            { -395.32f, 25.14f, -148.80f },
            { -379.24f, 20.60f, -148.78f },
            { -369.12f, 24.82f, -148.13f },
            { -368.38f, 32.95f, -142.67f },
            { -368.95f, 41.51f, -136.56f },
            { -369.51f, 49.80f, -130.60f },
            { -370.80f, 68.92f, -130.44f },
            { -369.93f, 77.01f, -131.85f },
            { -355.99f, 90.52f, -131.85f },
            { -344.84f, 102.58f, -131.85f },
            { -336.51f, 118.18f, -131.85f },
            { -331.72f, 135.05f, -131.86f },
            { -331.31f, 143.88f, -131.86f },
            { -318.99f, 155.50f, -135.76f },
            { -310.60f, 156.40f, -138.06f },
            { -302.07f, 151.90f, -141.11f },
            { -298.49f, 144.21f, -144.48f },
            { -300.65f, 136.07f, -146.99f },
            { -307.04f, 130.81f, -149.06f },
            { -315.40f, 129.68f, -151.93f },
            { -323.46f, 133.73f, -155.63f },
            { -327.09f, 141.46f, -158.64f },
            { -325.40f, 149.47f, -160.84f },
            { -318.60f, 155.94f, -163.94f },
            { -309.49f, 157.38f, -166.69f },
            { -297.87f, 146.14f, -171.72f },
            { -297.79f, 126.63f, -172.99f },
            { -293.00f, 119.60f, -173.00f },
            { -300.24f, 101.38f, -173.00f },
            { -315.69f, 97.16f, -172.83f },
            { -333.17f, 95.09f, -172.95f },
            { -350.13f, 93.08f, -172.99f },
            { -367.31f, 91.05f, -172.95f },
            { -387.62f, 93.91f, -172.93f },
            { -404.83f, 97.24f, -172.93f },
            { -424.47f, 97.07f, -190.42f },
            { -423.65f, 86.20f, -190.33f },
            { -435.20f, 95.04f, -183.61f },
            { -442.16f, 100.06f, -190.45f },
            { -452.26f, 104.42f, -189.79f },
        });
}
