// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 1325400066 (Shadowforge Lock), 18 anchors over 288yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_1325400066()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { 685.67f, 147.74f, -72.21f },
            { 682.66f, 127.88f, -73.32f },
            { 676.09f, 112.51f, -73.14f },
            { 668.62f, 97.41f, -73.30f },
            { 660.62f, 82.08f, -73.24f },
            { 652.81f, 66.78f, -73.07f },
            { 644.78f, 50.69f, -73.31f },
            { 632.44f, 39.30f, -73.62f },
            { 617.05f, 30.93f, -73.05f },
            { 602.14f, 22.76f, -72.59f },
            { 588.02f, 13.52f, -69.32f },
            { 576.85f, 1.05f, -69.48f },
            { 567.84f, -13.03f, -68.89f },
            { 564.03f, -29.73f, -63.79f },
            { 560.54f, -46.08f, -60.19f },
            { 567.66f, -52.96f, -59.44f },
            { 585.31f, -51.45f, -60.03f },
            { 604.63f, -51.33f, -60.05f },
        });
}
