// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400079 (Atal'ai Defender (Loro)), 17 anchors over 201yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400079()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400079,
        {
            { -535.98f, 61.02f, -65.58f },
            { -552.68f, 62.69f, -68.81f },
            { -567.95f, 56.61f, -68.83f },
            { -574.16f, 50.37f, -68.83f },
            { -585.66f, 47.38f, -68.83f },
            { -590.04f, 57.25f, -67.56f },
            { -585.05f, 63.66f, -62.04f },
            { -579.28f, 69.65f, -56.55f },
            { -572.58f, 74.58f, -53.43f },
            { -557.33f, 62.35f, -53.39f },
            { -546.75f, 48.82f, -52.92f },
            { -535.12f, 36.82f, -53.35f },
            { -523.37f, 24.87f, -53.34f },
            { -505.75f, 25.69f, -54.77f },
            { -497.87f, 23.37f, -58.02f },
            { -490.09f, 21.12f, -61.60f },
            { -482.19f, 18.26f, -64.77f },
        });
}
