// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9033 (General Angerforge), 29 anchors over 457yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9033()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9033,
        {
            { 596.43f, -188.50f, -53.90f },
            { 593.26f, -171.83f, -53.61f },
            { 589.22f, -155.12f, -52.73f },
            { 585.53f, -136.72f, -52.42f },
            { 585.03f, -119.87f, -48.71f },
            { 582.90f, -103.32f, -45.44f },
            { 600.96f, -101.54f, -45.46f },
            { 617.77f, -103.58f, -46.20f },
            { 633.98f, -117.57f, -46.20f },
            { 648.15f, -126.47f, -46.23f },
            { 663.99f, -133.48f, -46.23f },
            { 679.84f, -139.66f, -46.23f },
            { 696.11f, -130.38f, -46.23f },
            { 708.99f, -118.58f, -45.91f },
            { 721.59f, -106.19f, -45.94f },
            { 733.81f, -93.67f, -45.93f },
            { 745.93f, -81.50f, -46.23f },
            { 756.91f, -68.38f, -46.23f },
            { 761.47f, -51.90f, -46.23f },
            { 751.93f, -47.40f, -46.23f },
            { 743.95f, -32.75f, -44.86f },
            { 736.07f, -17.98f, -46.22f },
            { 719.93f, -9.64f, -45.49f },
            { 705.99f, -1.19f, -45.92f },
            { 694.69f, 11.78f, -45.50f },
            { 689.39f, 19.23f, -49.45f },
            { 679.00f, 33.26f, -55.91f },
            { 668.97f, 33.69f, -59.70f },
            { 661.81f, 28.56f, -60.04f },
        });
}
