// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400069 (Atal'ai Statue 4), 19 anchors over 265yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400069()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400069,
        {
            { -490.37f, 140.73f, -148.74f },
            { -486.30f, 158.37f, -148.78f },
            { -484.84f, 167.83f, -148.80f },
            { -500.64f, 173.32f, -148.80f },
            { -508.77f, 176.30f, -148.80f },
            { -525.01f, 165.63f, -148.71f },
            { -538.01f, 152.99f, -148.72f },
            { -548.58f, 139.02f, -148.76f },
            { -553.46f, 123.08f, -148.80f },
            { -557.96f, 106.25f, -148.80f },
            { -559.54f, 90.16f, -148.80f },
            { -555.00f, 73.97f, -148.80f },
            { -550.93f, 57.82f, -148.80f },
            { -542.15f, 42.37f, -148.80f },
            { -528.62f, 29.48f, -148.80f },
            { -520.27f, 31.71f, -148.80f },
            { -522.85f, 39.46f, -148.80f },
            { -517.43f, 46.60f, -148.80f },
            { -506.60f, 49.06f, -148.74f },
        });
}
