// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400071 (Atal'ai Statue 6), 18 anchors over 262yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400071()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400071,
        {
            { -439.33f, 139.14f, -148.74f },
            { -421.90f, 143.11f, -148.78f },
            { -414.01f, 145.76f, -148.80f },
            { -414.55f, 156.85f, -148.80f },
            { -408.63f, 162.29f, -148.80f },
            { -395.08f, 150.35f, -148.80f },
            { -385.80f, 136.14f, -148.80f },
            { -381.37f, 119.38f, -148.80f },
            { -376.58f, 102.86f, -148.80f },
            { -376.73f, 85.65f, -148.80f },
            { -381.54f, 69.14f, -148.80f },
            { -386.33f, 52.56f, -148.80f },
            { -397.89f, 37.99f, -148.80f },
            { -410.37f, 25.38f, -148.80f },
            { -424.20f, 14.81f, -148.80f },
            { -444.28f, 19.10f, -148.60f },
            { -448.22f, 28.65f, -148.06f },
            { -447.10f, 40.01f, -148.74f },
        });
}
