// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 8983 (Golem Lord Argelmach), 31 anchors over 456yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_8983()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 8983,
        {
            { 609.65f, -48.07f, -59.52f },
            { 592.99f, -53.86f, -59.42f },
            { 584.07f, -54.94f, -59.43f },
            { 583.99f, -62.76f, -55.33f },
            { 591.14f, -67.20f, -50.91f },
            { 604.88f, -76.74f, -44.93f },
            { 620.41f, -87.51f, -45.26f },
            { 629.71f, -105.10f, -45.38f },
            { 637.49f, -120.18f, -45.72f },
            { 652.38f, -128.44f, -45.71f },
            { 668.03f, -135.55f, -45.69f },
            { 687.83f, -137.60f, -45.72f },
            { 700.61f, -126.86f, -45.23f },
            { 713.43f, -114.05f, -45.57f },
            { 725.96f, -101.60f, -45.57f },
            { 737.85f, -89.70f, -45.24f },
            { 749.93f, -76.29f, -45.67f },
            { 757.49f, -61.23f, -45.26f },
            { 752.96f, -44.86f, -45.61f },
            { 748.01f, -28.06f, -45.70f },
            { 745.68f, -19.87f, -45.69f },
            { 730.95f, -8.65f, -45.56f },
            { 715.02f, 0.27f, -45.95f },
            { 716.84f, 9.76f, -44.65f },
            { 722.42f, 16.28f, -44.34f },
            { 731.52f, 18.38f, -47.76f },
            { 741.03f, 19.23f, -52.23f },
            { 758.73f, 22.96f, -53.64f },
            { 775.54f, 15.87f, -53.12f },
            { 794.02f, 7.30f, -53.14f },
            { 802.82f, 8.69f, -52.96f },
        });
}
