// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5719 (Morphaz), 11 anchors over 164yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5719()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5719,
        {
            { -467.78f, 109.73f, -94.47f },
            { -474.90f, 93.67f, -94.19f },
            { -485.32f, 89.53f, -93.08f },
            { -503.80f, 91.01f, -91.26f },
            { -521.82f, 92.53f, -91.28f },
            { -541.23f, 92.61f, -90.38f },
            { -558.81f, 92.53f, -90.51f },
            { -577.71f, 92.64f, -90.33f },
            { -594.61f, 92.49f, -90.33f },
            { -612.92f, 90.99f, -90.33f },
            { -621.16f, 91.84f, -90.50f },
        });
}
