// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9056 (Fineous Darkvire), 9 anchors over 106yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9056()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9056,
        {
            { 896.48f, -276.56f, -71.32f },
            { 904.96f, -281.88f, -71.51f },
            { 913.74f, -296.44f, -71.77f },
            { 922.34f, -310.71f, -71.76f },
            { 926.61f, -317.79f, -71.76f },
            { 935.34f, -313.53f, -71.22f },
            { 948.45f, -327.14f, -71.22f },
            { 961.32f, -338.34f, -71.30f },
            { 970.51f, -337.58f, -70.62f },
        });
}
