// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5710 (Jammal'an the Prophet), 17 anchors over 247yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5710()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5710,
        {
            { -458.81f, 87.93f, -94.03f },
            { -468.35f, 71.68f, -92.53f },
            { -469.83f, 62.86f, -91.95f },
            { -480.52f, 49.13f, -90.92f },
            { -490.02f, 34.39f, -90.60f },
            { -503.82f, 18.92f, -90.33f },
            { -507.79f, 2.94f, -90.33f },
            { -516.70f, -12.81f, -90.33f },
            { -525.57f, -28.71f, -90.33f },
            { -534.05f, -44.54f, -90.33f },
            { -540.08f, -61.07f, -90.30f },
            { -532.76f, -70.50f, -90.23f },
            { -516.97f, -75.13f, -90.23f },
            { -508.86f, -73.33f, -90.41f },
            { -491.37f, -82.79f, -90.49f },
            { -481.59f, -78.56f, -90.23f },
            { -473.27f, -80.17f, -90.23f },
        });
}
