// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5720 (Weaver), 6 anchors over 73yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5720()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5720,
        {
            { -512.38f, 38.09f, -90.33f },
            { -502.46f, 53.95f, -91.32f },
            { -490.98f, 68.59f, -90.96f },
            { -480.96f, 83.32f, -93.13f },
            { -476.98f, 91.46f, -93.96f },
            { -485.84f, 93.79f, -93.79f },
        });
}
