// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5709 (Shade of Eranikus), 6 anchors over 79yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5709()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5709,
        {
            { -664.05f, 56.37f, -90.83f },
            { -665.13f, 39.23f, -90.84f },
            { -663.29f, 20.25f, -90.84f },
            { -661.61f, 2.82f, -90.84f },
            { -660.15f, -14.16f, -90.84f },
            { -659.45f, -22.67f, -90.84f },
        });
}
