// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 1325400065 (Ring of Law), 21 anchors over 295yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_1325400065()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 1325400065,
        {
            { 612.55f, -198.02f, -84.26f },
            { 593.51f, -201.12f, -84.50f },
            { 595.04f, -210.75f, -84.51f },
            { 611.10f, -219.76f, -84.05f },
            { 619.87f, -237.99f, -82.39f },
            { 620.33f, -246.37f, -83.01f },
            { 615.97f, -255.94f, -83.17f },
            { 599.46f, -264.51f, -82.93f },
            { 582.08f, -265.83f, -78.86f },
            { 563.49f, -258.71f, -73.88f },
            { 549.46f, -248.94f, -69.67f },
            { 534.77f, -240.05f, -66.49f },
            { 528.72f, -231.97f, -62.45f },
            { 529.32f, -223.97f, -59.31f },
            { 539.79f, -209.47f, -55.59f },
            { 555.72f, -198.15f, -52.22f },
            { 568.10f, -182.04f, -52.05f },
            { 576.00f, -173.37f, -52.38f },
            { 581.42f, -181.68f, -52.76f },
            { 580.56f, -190.04f, -52.93f },
            { 592.91f, -188.93f, -53.93f },
        });
}
