// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9319 (Houndmaster Grebmar), 29 anchors over 456yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9319()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9319,
        {
            { 313.26f, -142.86f, -70.39f },
            { 318.68f, -136.36f, -68.86f },
            { 329.84f, -134.31f, -64.42f },
            { 338.85f, -137.23f, -64.42f },
            { 363.61f, -131.96f, -64.20f },
            { 380.68f, -128.59f, -64.42f },
            { 397.92f, -124.80f, -64.43f },
            { 415.38f, -120.99f, -65.11f },
            { 433.14f, -116.43f, -64.66f },
            { 451.18f, -113.21f, -63.57f },
            { 467.41f, -114.53f, -62.22f },
            { 484.06f, -117.10f, -61.94f },
            { 501.35f, -119.99f, -61.71f },
            { 517.81f, -122.73f, -62.65f },
            { 535.31f, -125.38f, -61.27f },
            { 554.33f, -124.88f, -62.04f },
            { 573.12f, -131.62f, -64.79f },
            { 589.10f, -135.86f, -68.76f },
            { 605.69f, -140.26f, -70.40f },
            { 621.82f, -145.44f, -70.99f },
            { 638.41f, -152.62f, -70.85f },
            { 648.14f, -169.64f, -70.70f },
            { 649.69f, -189.56f, -74.80f },
            { 651.70f, -206.09f, -77.60f },
            { 647.87f, -221.86f, -82.19f },
            { 642.68f, -228.57f, -82.64f },
            { 629.56f, -231.40f, -81.72f },
            { 621.68f, -229.42f, -82.40f },
            { 612.12f, -215.69f, -83.68f },
        });
}
