// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9018 (High Interrogator Gerstahn), 16 anchors over 273yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9018()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9018,
        {
            { 456.93f, 34.09f, -68.09f },
            { 460.66f, 17.40f, -70.34f },
            { 465.06f, -0.28f, -69.95f },
            { 469.81f, -19.17f, -67.43f },
            { 472.22f, -40.55f, -63.00f },
            { 469.90f, -60.36f, -61.19f },
            { 466.10f, -76.68f, -62.72f },
            { 460.87f, -93.74f, -61.50f },
            { 450.17f, -107.70f, -63.62f },
            { 430.41f, -113.33f, -65.01f },
            { 409.64f, -117.54f, -64.88f },
            { 390.11f, -124.04f, -64.65f },
            { 374.02f, -128.43f, -64.42f },
            { 356.15f, -134.13f, -64.42f },
            { 337.76f, -135.77f, -64.42f },
            { 329.50f, -133.91f, -64.71f },
        });
}
