// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5715 (Hukku), 21 anchors over 244yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5715()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5715,
        {
            { -480.00f, 18.93f, -64.73f },
            { -487.56f, 16.00f, -63.84f },
            { -496.80f, 20.20f, -59.87f },
            { -504.39f, 23.79f, -56.04f },
            { -512.49f, 26.39f, -53.93f },
            { -513.46f, 16.67f, -53.95f },
            { -497.80f, 11.12f, -53.95f },
            { -481.35f, 6.15f, -53.29f },
            { -464.91f, 3.20f, -52.23f },
            { -444.76f, 7.16f, -53.38f },
            { -428.37f, 8.96f, -53.77f },
            { -412.07f, 10.46f, -53.95f },
            { -395.73f, 10.67f, -53.84f },
            { -387.44f, 10.04f, -57.44f },
            { -379.23f, 9.41f, -62.31f },
            { -370.24f, 8.73f, -68.30f },
            { -364.44f, 17.80f, -69.39f },
            { -369.74f, 24.09f, -69.39f },
            { -386.15f, 27.46f, -69.39f },
            { -394.81f, 32.80f, -69.39f },
            { -398.52f, 40.00f, -67.76f },
        });
}
