// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400070 (Atal'ai Statue 5), 23 anchors over 363yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400070()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400070,
        {
            { -496.53f, 52.04f, -148.74f },
            { -513.18f, 47.22f, -148.81f },
            { -521.18f, 44.27f, -148.80f },
            { -518.72f, 22.54f, -148.80f },
            { -513.94f, 15.48f, -148.80f },
            { -497.58f, 10.30f, -148.78f },
            { -480.46f, 5.41f, -148.80f },
            { -463.35f, 3.50f, -148.80f },
            { -446.07f, 8.28f, -148.80f },
            { -429.61f, 12.53f, -148.80f },
            { -414.45f, 21.15f, -148.80f },
            { -401.89f, 34.28f, -148.80f },
            { -390.27f, 46.20f, -148.80f },
            { -382.89f, 63.33f, -148.80f },
            { -377.81f, 81.77f, -148.80f },
            { -375.54f, 98.59f, -148.80f },
            { -380.15f, 116.38f, -148.80f },
            { -384.48f, 133.07f, -148.80f },
            { -392.74f, 148.18f, -148.80f },
            { -406.57f, 160.73f, -148.80f },
            { -414.78f, 161.80f, -148.80f },
            { -413.75f, 145.84f, -148.80f },
            { -430.68f, 141.76f, -148.74f },
        });
}
