// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9017 (Lord Incendius), 35 anchors over 550yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9017()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9017,
        {
            { 471.42f, -2.29f, -69.71f },
            { 485.27f, 7.03f, -70.59f },
            { 500.69f, 13.31f, -70.58f },
            { 517.52f, 12.61f, -70.73f },
            { 534.33f, 12.09f, -70.54f },
            { 551.24f, 11.58f, -70.22f },
            { 568.43f, 11.06f, -70.50f },
            { 586.64f, 11.36f, -69.04f },
            { 603.17f, 5.20f, -70.73f },
            { 618.54f, -0.80f, -73.58f },
            { 630.56f, -12.97f, -73.24f },
            { 641.64f, -26.33f, -72.97f },
            { 651.71f, -40.21f, -73.28f },
            { 662.91f, -52.77f, -73.12f },
            { 675.14f, -64.66f, -72.71f },
            { 687.06f, -76.26f, -71.98f },
            { 693.14f, -82.17f, -72.38f },
            { 698.77f, -76.07f, -71.11f },
            { 707.19f, -78.18f, -71.31f },
            { 714.86f, -93.03f, -71.51f },
            { 723.31f, -107.56f, -71.72f },
            { 735.49f, -119.20f, -71.96f },
            { 748.32f, -131.47f, -72.45f },
            { 747.73f, -150.33f, -72.26f },
            { 763.98f, -160.46f, -72.87f },
            { 777.63f, -170.37f, -72.99f },
            { 790.44f, -182.47f, -73.56f },
            { 803.06f, -194.21f, -73.07f },
            { 812.43f, -191.20f, -72.42f },
            { 825.71f, -204.88f, -72.56f },
            { 839.79f, -219.40f, -72.07f },
            { 851.70f, -231.67f, -71.76f },
            { 867.09f, -238.44f, -71.76f },
            { 875.54f, -256.60f, -71.81f },
            { 881.46f, -262.40f, -71.83f },
        });
}
