// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400075 (Atal'ai Defender (Mijan)), 21 anchors over 253yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400075()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400075,
        {
            { -319.24f, 99.90f, -131.85f },
            { -335.32f, 107.55f, -131.32f },
            { -351.50f, 114.82f, -130.56f },
            { -366.00f, 126.01f, -131.26f },
            { -369.75f, 166.96f, -119.53f },
            { -363.18f, 164.07f, -115.29f },
            { -355.64f, 160.90f, -109.57f },
            { -354.19f, 152.17f, -107.25f },
            { -362.92f, 154.90f, -100.47f },
            { -370.53f, 157.92f, -94.69f },
            { -378.33f, 161.03f, -89.57f },
            { -379.58f, 170.53f, -87.83f },
            { -371.46f, 168.24f, -81.75f },
            { -363.94f, 164.91f, -75.70f },
            { -356.36f, 161.65f, -69.99f },
            { -349.48f, 157.11f, -68.93f },
            { -352.07f, 146.36f, -68.93f },
            { -366.11f, 132.72f, -68.93f },
            { -372.37f, 127.34f, -68.93f },
            { -390.29f, 127.21f, -65.45f },
            { -398.60f, 130.07f, -66.06f },
        });
}
