// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5713 (Gasher), 23 anchors over 288yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5713()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5713,
        {
            { -530.27f, 140.10f, -65.54f },
            { -537.86f, 154.41f, -68.54f },
            { -550.82f, 163.96f, -68.83f },
            { -565.73f, 170.21f, -68.83f },
            { -565.39f, 180.91f, -68.83f },
            { -553.37f, 181.21f, -61.43f },
            { -545.47f, 179.50f, -56.21f },
            { -537.88f, 176.55f, -53.46f },
            { -536.42f, 165.27f, -53.47f },
            { -542.79f, 148.90f, -53.44f },
            { -550.06f, 132.14f, -53.60f },
            { -555.40f, 116.68f, -53.42f },
            { -558.40f, 100.04f, -53.35f },
            { -557.95f, 91.85f, -53.95f },
            { -570.87f, 79.55f, -53.43f },
            { -581.79f, 67.36f, -59.63f },
            { -587.95f, 62.00f, -64.26f },
            { -593.63f, 56.18f, -67.98f },
            { -587.13f, 46.79f, -68.83f },
            { -578.77f, 47.55f, -68.83f },
            { -565.51f, 59.03f, -68.83f },
            { -549.67f, 62.88f, -67.81f },
            { -541.39f, 62.05f, -64.81f },
        });
}
