// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400066 (Atal'ai Statue 1), 45 anchors over 578yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400066()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { -298.44f, 73.78f, -90.33f },
            { -297.36f, 55.88f, -91.37f },
            { -301.33f, 40.46f, -91.76f },
            { -315.28f, 32.75f, -97.55f },
            { -322.63f, 36.54f, -100.11f },
            { -327.25f, 43.72f, -102.74f },
            { -326.11f, 51.98f, -105.07f },
            { -317.93f, 59.84f, -108.68f },
            { -309.85f, 60.30f, -111.07f },
            { -302.64f, 56.31f, -114.83f },
            { -299.89f, 48.01f, -116.63f },
            { -304.23f, 36.96f, -120.72f },
            { -311.88f, 33.61f, -122.78f },
            { -319.94f, 34.64f, -125.71f },
            { -326.49f, 39.99f, -129.74f },
            { -332.49f, 55.43f, -131.86f },
            { -337.10f, 72.23f, -131.86f },
            { -341.99f, 78.73f, -131.85f },
            { -357.81f, 82.89f, -131.85f },
            { -366.08f, 81.37f, -131.85f },
            { -370.74f, 74.70f, -131.85f },
            { -370.30f, 56.75f, -128.80f },
            { -368.83f, 47.13f, -132.22f },
            { -368.75f, 39.53f, -137.21f },
            { -366.04f, 31.70f, -143.03f },
            { -367.95f, 22.70f, -147.39f },
            { -377.51f, 20.45f, -148.84f },
            { -396.34f, 25.16f, -148.80f },
            { -413.67f, 19.03f, -148.57f },
            { -431.20f, 9.43f, -148.35f },
            { -447.26f, 7.71f, -148.80f },
            { -464.63f, 3.54f, -148.80f },
            { -482.71f, 6.13f, -148.80f },
            { -499.14f, 10.69f, -148.77f },
            { -515.35f, 16.55f, -148.80f },
            { -527.89f, 28.57f, -148.80f },
            { -540.16f, 40.58f, -148.80f },
            { -549.95f, 54.38f, -148.80f },
            { -554.36f, 71.73f, -148.80f },
            { -558.97f, 88.31f, -148.80f },
            { -559.74f, 96.93f, -148.80f },
            { -548.33f, 110.20f, -148.80f },
            { -542.17f, 115.67f, -148.80f },
            { -527.87f, 106.26f, -148.74f },
            { -520.01f, 99.21f, -148.74f },
        });
}
