// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400076 (Atal'ai Defender (Zul'Lor)), 17 anchors over 205yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400076()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400076,
        {
            { -399.07f, 129.69f, -66.13f },
            { -383.12f, 125.96f, -68.49f },
            { -367.38f, 130.73f, -68.93f },
            { -354.75f, 140.75f, -68.93f },
            { -346.39f, 142.95f, -68.93f },
            { -344.40f, 132.05f, -66.54f },
            { -349.34f, 125.35f, -61.03f },
            { -355.00f, 119.47f, -55.41f },
            { -361.73f, 114.90f, -53.72f },
            { -370.12f, 118.53f, -53.33f },
            { -378.80f, 132.82f, -53.43f },
            { -386.86f, 147.75f, -53.35f },
            { -399.92f, 158.04f, -53.34f },
            { -415.54f, 163.43f, -53.43f },
            { -434.64f, 167.57f, -57.76f },
            { -442.41f, 170.45f, -61.50f },
            { -450.54f, 171.87f, -64.51f },
        });
}
