// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 349, boss 13596 (Rotgrip), 10 anchors over 130yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute349_13596()
{
    DungeonClearRouteRegistry::Register(349, DUNGEON_DIFFICULTY_NORMAL, 13596,
        {
            { 24.91f, 31.54f, -124.83f },
            { 14.10f, 18.99f, -125.58f },
            { 8.71f, 12.72f, -127.58f },
            { 15.63f, -2.75f, -127.72f },
            { 16.75f, -20.00f, -127.64f },
            { 17.24f, -37.42f, -127.65f },
            { 17.91f, -55.70f, -127.85f },
            { 18.23f, -64.55f, -127.66f },
            { 27.56f, -64.29f, -127.31f },
            { 27.96f, -81.48f, -126.07f },
        });
}
