// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400078 (Atal'ai Defender (Gasher)), 24 anchors over 297yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400078()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400078,
        {
            { -530.32f, 140.53f, -65.43f },
            { -541.55f, 158.20f, -68.83f },
            { -548.40f, 163.46f, -68.83f },
            { -564.41f, 168.12f, -68.83f },
            { -568.89f, 175.24f, -68.83f },
            { -564.00f, 182.08f, -68.79f },
            { -555.65f, 181.69f, -62.80f },
            { -547.78f, 180.02f, -57.91f },
            { -539.82f, 178.23f, -53.43f },
            { -534.11f, 172.40f, -53.53f },
            { -539.16f, 156.85f, -53.48f },
            { -546.16f, 141.54f, -52.76f },
            { -553.30f, 123.83f, -53.37f },
            { -558.09f, 107.49f, -53.95f },
            { -558.80f, 90.31f, -53.79f },
            { -571.81f, 78.71f, -53.44f },
            { -582.63f, 66.31f, -59.76f },
            { -589.88f, 60.44f, -65.27f },
            { -595.91f, 53.58f, -68.83f },
            { -587.31f, 46.77f, -68.83f },
            { -578.65f, 47.56f, -68.83f },
            { -565.25f, 59.29f, -68.83f },
            { -549.10f, 62.86f, -67.53f },
            { -540.54f, 61.92f, -65.41f },
        });
}
