// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400065 (Weaver & Dreamscythe), 4 anchors over 43yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400065()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400065,
        {
            { -494.27f, 66.67f, -90.44f },
            { -487.18f, 70.81f, -92.19f },
            { -479.42f, 86.42f, -94.43f },
            { -471.53f, 102.72f, -94.79f },
        });
}
