// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400067 (Atal'ai Statue 2), 24 anchors over 362yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400067()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400067,
        {
            { -519.53f, 98.78f, -148.74f },
            { -532.16f, 110.51f, -148.80f },
            { -539.41f, 116.03f, -148.80f },
            { -549.52f, 108.98f, -148.80f },
            { -555.35f, 116.87f, -148.80f },
            { -551.14f, 133.19f, -148.80f },
            { -543.14f, 147.48f, -148.72f },
            { -530.66f, 159.48f, -148.71f },
            { -518.16f, 172.27f, -148.71f },
            { -502.39f, 179.19f, -148.80f },
            { -484.66f, 184.02f, -148.80f },
            { -467.09f, 187.23f, -148.84f },
            { -449.83f, 184.12f, -148.87f },
            { -431.92f, 179.44f, -148.84f },
            { -415.52f, 170.76f, -148.80f },
            { -404.10f, 158.59f, -148.80f },
            { -391.79f, 146.63f, -148.80f },
            { -383.72f, 130.79f, -148.80f },
            { -379.39f, 112.95f, -148.80f },
            { -375.56f, 96.23f, -148.80f },
            { -378.06f, 88.01f, -148.80f },
            { -391.98f, 75.78f, -148.82f },
            { -403.17f, 79.70f, -148.81f },
            { -410.02f, 88.88f, -148.75f },
        });
}
