// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 1325400068 (Atal'ai Statue 3), 18 anchors over 271yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_1325400068()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 1325400068,
        {
            { -415.73f, 93.12f, -148.74f },
            { -404.03f, 80.59f, -148.77f },
            { -397.60f, 74.82f, -148.84f },
            { -383.35f, 84.89f, -148.69f },
            { -376.49f, 90.38f, -148.80f },
            { -377.73f, 107.52f, -148.80f },
            { -382.00f, 124.94f, -148.80f },
            { -387.73f, 140.75f, -148.80f },
            { -398.42f, 153.63f, -148.80f },
            { -410.69f, 165.65f, -148.80f },
            { -424.10f, 176.56f, -148.81f },
            { -440.74f, 181.91f, -148.87f },
            { -457.25f, 185.90f, -148.87f },
            { -474.45f, 186.83f, -148.80f },
            { -491.04f, 182.21f, -148.80f },
            { -498.99f, 178.58f, -148.80f },
            { -485.70f, 161.83f, -148.80f },
            { -493.29f, 146.79f, -148.74f },
        });
}
