// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5712 (Zolo), 21 anchors over 255yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5712()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5712,
        {
            { -460.42f, 169.07f, -65.97f },
            { -453.01f, 172.44f, -65.35f },
            { -436.20f, 167.66f, -59.11f },
            { -428.43f, 163.90f, -55.18f },
            { -420.17f, 163.34f, -53.94f },
            { -417.94f, 172.52f, -53.95f },
            { -432.67f, 181.48f, -53.95f },
            { -451.87f, 184.38f, -53.42f },
            { -468.15f, 187.12f, -53.95f },
            { -484.70f, 184.83f, -53.95f },
            { -494.54f, 186.52f, -53.38f },
            { -509.75f, 180.81f, -53.97f },
            { -525.81f, 178.36f, -54.10f },
            { -542.11f, 179.87f, -55.36f },
            { -550.35f, 180.88f, -60.95f },
            { -557.21f, 181.48f, -65.74f },
            { -565.40f, 181.24f, -69.40f },
            { -567.06f, 170.48f, -69.40f },
            { -560.88f, 165.25f, -69.40f },
            { -544.67f, 162.46f, -69.40f },
            { -532.77f, 151.06f, -68.73f },
        });
}
