// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5721 (Dreamscythe), 4 anchors over 44yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5721()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5721,
        {
            { -381.62f, 83.72f, -90.27f },
            { -399.02f, 79.61f, -90.37f },
            { -412.22f, 66.24f, -90.50f },
            { -417.10f, 59.52f, -90.56f },
        });
}
