-- Puts back what shadowfang_keep_as_rows.sql replaced, as t1_world had it when the migration
-- was written (scripts/tier2/a32_shadowfang_keep.py). The rows the migration added are removed.

DELETE FROM `conditions` WHERE `condition_entry` IN (33004, 33005);
DELETE FROM `creature_ai_events` WHERE `id` IN (444408, 1000001);
DELETE FROM `creature_ai_scripts` WHERE `id` IN (444408, 1000001);
DELETE FROM `creature_ai_scripts` WHERE `id` = 392705 AND `command` = 11 AND `comments` = 'Wolf Master Nandos - open Arugal''s Door (A32)';
DELETE FROM `creature_ai_scripts` WHERE `id` = 462704 AND `command` = 37 AND `comments` = 'Arugal''s Voidwalker - one more dead, slot 7 (A32)';
DELETE FROM `creature_ai_scripts` WHERE `id` = 462704 AND `command` = 11 AND `comments` = 'Arugal''s Voidwalker - the fourth opens the Sorcerer''s Door (A32)';
DELETE FROM `gameobject_spawn_state` WHERE `guid` = 20835 AND `ord` = 0;
DELETE FROM `gameobject_spawn_state` WHERE `guid` = 33785 AND `ord` = 0;
DELETE FROM `gameobject_spawn_state` WHERE `guid` = 33241 AND `ord` = 0;
-- The shared conditions go only once nothing names them: the other migration that writes them is then not applied either.
DELETE FROM `conditions` WHERE `condition_entry` = 532001 AND NOT EXISTS (SELECT 1 FROM `creature_ai_events` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `creature_ai_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `generic_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `gameobject_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `gossip_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `event_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `creature_movement_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `quest_start_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `quest_end_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `spell_scripts` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `gossip_menu` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `gossip_menu_option` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `gameobject_spawn_state` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM `areatrigger_generic_script` WHERE `condition_id` = 532001) AND NOT EXISTS (SELECT 1 FROM (SELECT * FROM `conditions`) c WHERE c.`type` < 0 AND 532001 IN (c.`value1`, c.`value2`, c.`value3`, c.`value4`));
DELETE FROM `conditions` WHERE `condition_entry` = 532003 AND NOT EXISTS (SELECT 1 FROM `creature_ai_events` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `creature_ai_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `generic_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `gameobject_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `gossip_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `event_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `creature_movement_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `quest_start_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `quest_end_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `spell_scripts` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `gossip_menu` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `gossip_menu_option` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `gameobject_spawn_state` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM `areatrigger_generic_script` WHERE `condition_id` = 532003) AND NOT EXISTS (SELECT 1 FROM (SELECT * FROM `conditions`) c WHERE c.`type` < 0 AND 532003 IN (c.`value1`, c.`value2`, c.`value3`, c.`value4`));
DELETE FROM `conditions` WHERE `condition_entry` = 33003 AND NOT EXISTS (SELECT 1 FROM `creature_ai_events` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `creature_ai_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `generic_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `gameobject_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `gossip_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `event_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `creature_movement_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `quest_start_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `quest_end_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `spell_scripts` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `gossip_menu` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `gossip_menu_option` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `gameobject_spawn_state` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM `areatrigger_generic_script` WHERE `condition_id` = 33003) AND NOT EXISTS (SELECT 1 FROM (SELECT * FROM `conditions`) c WHERE c.`type` < 0 AND 33003 IN (c.`value1`, c.`value2`, c.`value3`, c.`value4`));
