-- Puts back what sunken_temple_as_rows.sql replaced, as t1_world had it when the migration
-- was written (scripts/tier2/a34_sunken_temple.py). The rows the migration added are removed.

UPDATE `creature_template` SET `ai_name` = '', `script_name` = 'npc_malfurion_stormrage', `flags_extra` = 32771 WHERE `entry` = 15362;
DELETE FROM `conditions` WHERE `condition_entry` IN (109012, 109013, 109020, 10109000, 10109010);
DELETE FROM `creature_ai_events` WHERE `id` IN (1536201, 1536202);
DELETE FROM `creature_ai_scripts` WHERE `id` IN (1536201, 1536202);
DELETE FROM `generic_scripts` WHERE `id` IN (1090001, 1090002);
DELETE FROM `event_scripts` WHERE `id` IN (3094, 3095, 3097, 3098, 3099, 3100);
DELETE FROM `areatrigger_generic_script` WHERE `trigger_id` = 4016 AND `script_id` = 1090001;
-- The shared conditions go only once nothing names them: the other migration that writes them is then not applied either.
DELETE FROM `conditions` WHERE `condition_entry` = 230000 AND NOT EXISTS (SELECT 1 FROM `creature_ai_events` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `creature_ai_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `generic_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `gameobject_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `gossip_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `event_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `creature_movement_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `quest_start_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `quest_end_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `spell_scripts` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `gossip_menu` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `gossip_menu_option` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `gameobject_spawn_state` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM `areatrigger_generic_script` WHERE `condition_id` = 230000) AND NOT EXISTS (SELECT 1 FROM (SELECT * FROM `conditions`) c WHERE c.`type` < 0 AND 230000 IN (c.`value1`, c.`value2`, c.`value3`, c.`value4`));
DELETE FROM `conditions` WHERE `condition_entry` = 230064 AND NOT EXISTS (SELECT 1 FROM `creature_ai_events` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `creature_ai_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `generic_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `gameobject_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `gossip_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `event_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `creature_movement_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `quest_start_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `quest_end_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `spell_scripts` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `gossip_menu` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `gossip_menu_option` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `gameobject_spawn_state` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM `areatrigger_generic_script` WHERE `condition_id` = 230064) AND NOT EXISTS (SELECT 1 FROM (SELECT * FROM `conditions`) c WHERE c.`type` < 0 AND 230064 IN (c.`value1`, c.`value2`, c.`value3`, c.`value4`));
